language: go
sudo: required
go:
  - 1.11.1
services:
  - docker
install: true
script: make travis
deploy:
  skip_cleanup: true
  provider: releases
  file:
    - "./dist/oracledb_exporter.linux-amd64"
    - "./dist/oracledb_exporter.darwin-amd64"
  on:
    repo: akolk/oracledb_exporter
    tags: true
    all_branches: true

after_success:
  docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
  docker push akolk/oracledb_exporter:latest
